openapi: 3.0.0
info:
  title: Clinician Triage Service Contract
  description: API contract for the Clinician Triage Service
  version: 1.0.0
  contact:
    name: David Dionise
    email: ddionise@projectronin.com
servers:
  - url: /api/v1
tags:
  - name: Care Team Response
    description: Endpoints for creating and updating clinician communication

paths:
  /add_care_team_response/{patientId}:
    post:
      deprecated: true
      tags:
        - Care Team Response
      description: Create a care team response for the associated patient
      summary: Create Care Team Response
      operationId: addCareTeamResponseDEPRECATED
      parameters:
        - name: patientId
          in: path
          required: true
          example: '10253'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - survey_response_id
              properties:
                survey_response_id:
                  type: integer
                status:
                  type: string
                custom_comment:
                  type: string
                comment:
                  type: string
            example:
              survey_response_id: 1025
              status: address_at_next
              custom_comment: Go do a thing
              comment: I instructed the patient to do a thing
        required: true
      responses:
        '200':
          description: Successful create/update of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponseExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"
  /sign_care_team_response/{patientId}:
    patch:
      deprecated: true
      tags:
        - Care Team Response
      description: Sign a care team response for the associated patient
      summary: Sign Care Team Response
      operationId: signCareTeamResponseDEPRECATED
      parameters:
        - name: patientId
          in: path
          required: true
          example: '10352'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - survey_response_id
              properties:
                survey_response_id:
                  type: integer
                comment:
                  type: string
            example:
              survey_response_id: 1025
              comment: I instructed the patient to do a thing
        required: true
      responses:
        '200':
          description: Successful signing of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponseExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"
  /care_team_response/:
    post:
      tags:
        - Care Team Response
      description: Create a care team response for the associated survey response
      summary: Create/Update Care Team Response
      operationId: createCareTeamResponse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - option
                - surveyResponseId
              properties:
                surveyResponseId:
                  type: string
                option:
                  type: string
                comment:
                  type: string
            example:
              surveyResponseId: 982735
              option: schedule_visit
              comment: You should get in to see the doctor this week
        required: true
      responses:
        '200':
          description: Successful creation of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponseExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"
    get:
      tags:
        - Care Team Response
      description: Fetch Care Team Responses
      summary: Fetch Care Team Responses
      operationId: fetchCareTeamResponses
      parameters:
        - in: query
          name: surveyResponseId
          required: false
          description: Required if `patientId` is not provided
          schema:
            type: string
        - in: query
          name: patientId
          required: false
          description: Required if `surveyResponseId` is not provided
          schema:
            type: string
      responses:
        '200':
          description: Successful creation of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponsesExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"
  /care_team_response/{careTeamResponseId}:
    patch:
      tags:
        - Care Team Response
      summary: Update Care Team Response
      description: >-
        Update the selected option and custom comment of a patient message
      operationId: updateCareTeamResponse
      parameters:
        - name: careTeamResponseId
          in: path
          required: true
          example: '543346'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - option
              properties:
                option:
                  type: string
                comment:
                  type: string
            example:
              option: schedule_visit
              comment: You should get in to see the doctor this week
        required: true
      responses:
        '200':
          description: Successful create of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponseExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"
  /care_team_response/{careTeamResponseId}/sign:
    patch:
      tags:
        - Care Team Response
      summary: Sign Care Team Response
      description: >-
        Sign a care team response. May include an internal note
      operationId: signCareTeamResponse
      parameters:
        - name: careTeamResponseId
          in: path
          required: true
          example: '543346'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                internal_note:
                  type: string
            example:
              internal_note: Patient needs blood drawn
        required: true
      responses:
        '200':
          description: Successful signing of care team response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/CareTeamResponse'
              examples:
                CareTeamResponseExample:
                  $ref: '#/components/examples/CareTeamResponseExample'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/BadRequestError"
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/NotFoundError"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/AbstractResponse"
                  - type: object
                    properties:
                      errors:
                        type: array
                        items:
                          $ref: "#/components/schemas/Error"
              examples:
                BadRequestError:
                  $ref: "#/components/examples/InternalServerError"

components:
  schemas:
    AbstractResponse:
      type: object
      properties:
        meta:
          type: object
          properties:
            links:
              type: object
              properties:
                self:
                  type: string
                  description: Path of the API request
              additionalProperties: true
            version:
              type: string
              description: Semver version of the API
    Responder:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    CareTeamResponse:
      description: >-
        Data pertaining to the messages that clinicians send to the patients,
        and notes that are stored for internal use
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
          deprecated: true
          description: >-
            (See `patient_message -> value`). Required if `patient_message ->
            value` is `null`
        display_status:
          type: string
          deprecated: true
          description: >-
            (See `patient_message -> display`). Required if `patient_message ->
            display` is `null`
          nullable: true
        custom_comment:
          type: string
          deprecated: true
          description: (See `patient_message -> comment`)
          nullable: true
        comment:
          type: string
          deprecated: true
          description: (See `internal_note`)
        patient_message:
          type: object
          properties:
            option:
              type: string
              description: >-
                Message sent from the clinician to the patient. Chosen from a
                set number of options. Required if `status` is `null`
            display:
              type: string
              description: >-
                The display value of the `patient_message -> option` enum.
                Required if `display_status` is `null`
              nullable: true
            comment:
              type: string
              description: Custom comment sent to patient from the clinician
              nullable: true
        internal_note:
          type: string
          description: Optional note that the clinician can store for internal use
          nullable: true
        responder:
          $ref: '#/components/schemas/Responder'
        signed_at:
          type: string
          format: date-time
          description: >-
            The date/time that the clinician signed the communication with the
            customer (if it was signed)
          nullable: true
        read_at:
          type: string
          format: date-time
          description: The date/time that the patient read the response
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the error
        title:
          type: string
          description: Human readable message the describes the type of failure
        detail_message:
          type: string
          description: Human readable message that describes the specific failure
        detail:
          type: object
          additionalProperties: true
          description: An object that can convey structured information to the client. The schema of the object MUST be definable based on the code attribute
          nullable: true
        code:
          type: string
          description: An application specific error code string. This MAY be included if there is value providing an opaque error classification that can be used to lookup relevant documentation
          nullable: true
        status:
          type: string
          description: HTTP status of the response
  examples:
    CareTeamResponseExample:
      summary: Care Team Response Example
      value:
        meta:
          links:
            self: /v1/care_team_response/10256
          version: 1.0.0
        data:
          id: 10256
          status: schedule_visit
          display_status: Schedule Visit
          custom_comment: You should get in to see the doctor this week
          comment: Patient needs blood drawn
          patient_message:
            option: schedule_visit
            display: Schedule Visit
            comment: You should get in to see the doctor this week
          internal_note: Patient needs blood drawn
          responder:
            id: 28639
            name: Charles Henri
            created_at: '2022-01-09T03:08:01.123Z'
            updated_at: '2022-02-16T04:28:45.723Z'
          read_at: '2023-01-12T09:48:54.826Z'
          signed_at: '2023-01-12T07:23:13.837Z'
          created_at: '2023-01-12T07:23:13.837Z'
          updated_at: '2023-01-12T07:23:13.837Z'
    CareTeamResponsesExample:
      summary: Care Team Response Example
      value:
        meta:
          links:
            self: /v1/care_team_response/10256
          version: 1.0.0
        data:
          - id: 10256
            status: schedule_visit
            display_status: Schedule Visit
            custom_comment: You should get in to see the doctor this week
            comment: Patient needs blood drawn
            patient_message:
              option: schedule_visit
              display: Schedule Visit
              comment: You should get in to see the doctor this week
            internal_note: Patient needs blood drawn
            responder:
              id: 28639
              name: Charles Henri
              created_at: '2022-01-09T03:08:01.123Z'
              updated_at: '2022-02-16T04:28:45.723Z'
            read_at: '2023-01-12T09:48:54.826Z'
            signed_at: '2023-01-12T07:23:13.837Z'
            created_at: '2023-01-12T07:23:13.837Z'
            updated_at: '2023-01-12T07:23:13.837Z'
    BadRequestError:
      summary: Bad Request Error Example
      value:
        meta:
          links:
            self: /v1/care_team_response/10256
          version: 1.0.0
        errors:
          - id: 179F5161-D264-422B-8E2E-72B721739922
            title: Invalid Attribute
            detail_message: Attribute 'count' must be a positive value.
            code: VALIDATE-25
            detail:
              field: count
              value: '-1'
              message: Must be a positive value
            status: '400'
    NotFoundError:
      summary: Resource Not Found Error Example
      value:
        meta:
          links:
            self: /v1/care_team_response/10256
          version: 1.0.0
        errors:
          - id: 179F5161-D264-422B-8E2E-72B721739922
            title: Resource Not Found
            detail_message: No survey response with the ID "10256" found
            status: '404'
    InternalServerError:
      summary: Internal Server Error
      value:
        meta:
          links:
            self: /v1/care_team_response/10256
          version: 1.0.0
        errors:
          - id: 179F5161-D264-422B-8E2E-72B721739922
            title: Internal Server Error
            detail_message: Lost connection with DB
            status: '500'