{
  "openapi": "3.0.2",
  "info": {
    "title": "Clinician Triage Service Contract",
    "description": "API contract for the Clinician Triage Service",
    "version": "2.0.0",
    "contact": {
      "name": "David Dionise",
      "email": "ddionise@projectronin.com"
    }
  },
  "servers": [
    {
      "url": "/api/v2"
    }
  ],
  "tags": [
    {
      "name": "Care Team Response",
      "description": "Endpoints for creating and updating clinician communication"
    },
    {
      "name": "Tenant Configuration",
      "description": "Tenant-specific configuration values"
    },
    {
      "name": "Care Team Response - Chokuto Cut-Over",
      "description": "Utilities for supporting the cut-over of care team response data from Chokuto to CTS"
    }
  ],
  "paths": {
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses/draft": {
      "put": {
        "tags": [
          "Care Team Response"
        ],
        "description": "Create or update a care team response draft",
        "summary": "Create/Update Care Team Response Draft",
        "operationId": "upsertCareTeamResponse",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CareTeamResponse_RequestBody"
              },
              "examples": {
                "CareTeamResponse_RequestBody": {
                  "$ref": "#/components/examples/CareTeamResponse_RequestBody"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "202": {
            "description": "Successful upsert of care team response draft",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CareTeamResponse_ResponseBody"
                },
                "examples": {
                  "CreateCareTeamResponse_ResponseBody": {
                    "$ref": "#/components/examples/DraftCareTeamResponse_ResponseBody"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses": {
      "post": {
        "tags": [
          "Care Team Response"
        ],
        "description": "Create a care team response for the associated questionnaire response",
        "summary": "Create Care Team Response",
        "operationId": "createCareTeamResponse",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CareTeamResponse_RequestBody"
              },
              "examples": {
                "CareTeamResponse_RequestBody": {
                  "$ref": "#/components/examples/CareTeamResponse_RequestBody"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful creation of care team response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CareTeamResponse_ResponseBody"
                },
                "examples": {
                  "CreateCareTeamResponse_ResponseBody": {
                    "$ref": "#/components/examples/CreateCareTeamResponse_ResponseBody"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  },
                  "DuplicateResource": {
                    "$ref": "#/components/examples/DuplicateResource"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Care Team Response"
        ],
        "summary": "Fetch Care Team Responses",
        "description": "Fetch care team responses for the patient app",
        "operationId": "fetchCareTeamResponse",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Max number of care team response objects to be returned",
            "schema": {
              "type": "integer"
            },
            "required": true,
            "example": 20
          },
          {
            "name": "page",
            "in": "query",
            "description": "Page number requested, starting at 0 as the first page",
            "schema": {
              "type": "integer"
            },
            "example": 2,
            "required": false
          },
          {
            "name": "includeRead",
            "in": "query",
            "description": "To include or filter out read care team responses",
            "schema": {
              "type": "boolean"
            },
            "required": false,
            "example": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully fetch care team response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FetchCareTeamResponses_ResponseBody"
                },
                "examples": {
                  "GetCareTeamResponseExample": {
                    "$ref": "#/components/examples/FetchCareTeamResponses_ResponseBody"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  },
                  "DuplicateResource": {
                    "$ref": "#/components/examples/DuplicateResource"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses/{careTeamResponseId}/finalize": {
      "patch": {
        "tags": [
          "Care Team Response"
        ],
        "summary": "Finalize Care Team Response",
        "description": "Finalize a care team response. May include an internal note",
        "operationId": "finalizeCareTeamResponse",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          },
          {
            "name": "careTeamResponseId",
            "in": "path",
            "required": true,
            "example": "a608bf12-8fa2-404c-ad99-163a487ffbb0",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/FinalizeCareTeamResponse_RequestBody"
              },
              "examples": {
                "FinalizeCareTeamResponse_RequestBody": {
                  "$ref": "#/components/examples/FinalizeCareTeamResponse_RequestBody"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful completion of care team response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CareTeamResponse_ResponseBody"
                },
                "examples": {
                  "CareTeamResponseExample": {
                    "$ref": "#/components/examples/FinalizeCareTeamResponse_ResponsBody"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ErrorResponse"
                      }
                    }
                  }
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ErrorResponse"
                      }
                    }
                  }
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "409": {
            "description": "Duplicate Completion",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ErrorResponse"
                      }
                    }
                  }
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/DuplicateFinalization"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ErrorResponse"
                      }
                    }
                  }
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses/read": {
      "patch": {
        "tags": [
          "Care Team Response"
        ],
        "summary": "Mark Care Team Response as Read",
        "description": "Mark a list of Care Team Responses as having been read by the patient",
        "operationId": "markCareTeamResponsesAsRead",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MarkCareTeamResponsesAsRead_RequestBody"
              },
              "examples": {
                "MarkCareTeamResponsesAsRead_RequestBody": {
                  "$ref": "#/components/examples/MarkCareTeamResponsesAsRead_RequestBody"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successfully updated the care team response as \"read\""
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses/unread": {
      "get": {
        "tags": [
          "Care Team Response"
        ],
        "summary": "Fetch Unread Care Team Response Count",
        "description": "Fetch unread care team response count for the patient app",
        "operationId": "fetchUnreadCareTeamResponseCount",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully fetch unread care team response count",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UnreadCareTeamResponseCount_ResponseBody"
                },
                "examples": {
                  "GetCareTeamResponseExample": {
                    "$ref": "#/components/examples/UnreadCareTeamResponseCount_ResponseBody"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  },
                  "DuplicateResource": {
                    "$ref": "#/components/examples/DuplicateResource"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/patients/{patientId}/care-team-responses/cut-over": {
      "put": {
        "tags": [
          "Care Team Response - Chokuto Cut-Over"
        ],
        "summary": "Sync Care Team Response Data",
        "description": "Temporary endpoint used to sync care team response data between Chokuto and CTS during the cut-over plan",
        "operationId": "careTeamResponseCutOver",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          },
          {
            "in": "path",
            "name": "patientId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "9d63650e-c289-11ed-afa1-0242ac120002"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CareTeamResponseCutOver_RequestBody"
              },
              "examples": {
                "CareTeamRequestCutOver_RequestBody": {
                  "$ref": "#/components/examples/CareTeamRequestCutOver_RequestBody"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successfully received care team response"
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/BadRequestError"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/NotFoundError"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "BadRequestError": {
                    "$ref": "#/components/examples/InternalServerError"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tenants/{tenantId}/triage-configuration": {
      "get": {
        "tags": [
          "Tenant Configuration"
        ],
        "description": "Fetch configuration values for the tenant",
        "summary": "Fetch Tenant Configuration",
        "operationId": "fetchTenantConfiguration",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "tenantId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "apposnd"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful fetch of tenant configuration",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TenantConfiguration_ResponseBody"
                },
                "examples": {
                  "TenantConfiguration_ResponseBody": {
                    "$ref": "#/components/examples/TenantConfiguration_ResponseBody"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CareTeamResponse_RequestBody": {
        "type": "object",
        "properties": {
          "questionnaireResponseId": {
            "type": "string"
          },
          "patientMessage": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string"
              },
              "display": {
                "type": "string"
              },
              "comment": {
                "type": "string"
              }
            },
            "required": [
              "code"
            ]
          }
        },
        "required": [
          "questionnaireResponseId",
          "patientMessage"
        ]
      },
      "CareTeamResponseCutOver_RequestBody": {
        "type": "object",
        "properties": {
          "questionnaireResponseId": {
            "type": "string"
          },
          "alertFeedbackId": {
            "type": "string"
          },
          "careTeamResponseId": {
            "type": "string"
          },
          "isDraft": {
            "type": "boolean"
          },
          "responder": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name"
            ]
          },
          "patientMessage": {
            "$ref": "#/components/schemas/PatientMessage"
          },
          "internalNote": {
            "type": "string",
            "description": "Optional note that the clinician can store for internal use",
            "nullable": true
          },
          "ehrWriteBackMessage": {
            "type": "string",
            "description": "Message sent to the EHR. Free text with formatted details of the care team response and associated questionnaire response"
          },
          "signedAt": {
            "type": "string",
            "format": "date-time",
            "description": "The date/time that the clinician finalized the communication with the patient",
            "nullable": true
          },
          "readAt": {
            "type": "string",
            "format": "date-time",
            "description": "The date/time that the patient read the response",
            "nullable": true
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "questionnaireResponseId",
          "isDraft",
          "responder",
          "patientMessage",
          "createdAt",
          "updatedAt"
        ]
      },
      "MarkCareTeamResponsesAsRead_RequestBody": {
        "type": "object",
        "properties": {
          "careTeamResponseIds": {
            "description": "List of Care Team Response ids to mark as read",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "careTeamResponseIds"
        ]
      },
      "FinalizeCareTeamResponse_RequestBody": {
        "type": "object",
        "properties": {
          "internalNote": {
            "type": "string"
          },
          "ehrWriteBackMessage": {
            "type": "string",
            "description": "Message sent to the EHR. Free text with formatted details of the care team response and associated questionnaire response"
          },
          "action": {
            "$ref": "#/components/schemas/FinalizeAction"
          }
        },
        "required": [
          "ehrWriteBackMessage",
          "action"
        ]
      },
      "UnreadCareTeamResponseCount_ResponseBody": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/Count"
          }
        }
      },
      "Count": {
        "type": "object",
        "properties": {
          "count": {
            "type": "integer"
          }
        },
        "required": [
          "count"
        ]
      },
      "FetchCareTeamResponses_ResponseBody": {
        "description": "Fetch data pertaining to the messages that clinicians send to the patients, and notes that are stored for internal use",
        "type": "object",
        "properties": {
          "paging": {
            "type": "object",
            "properties": {
              "page": {
                "type": "integer"
              },
              "limit": {
                "type": "integer"
              }
            },
            "required": [
              "page",
              "limit"
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CareTeamResponse"
            }
          }
        },
        "required": [
          "paging",
          "data"
        ]
      },
      "CareTeamResponse_ResponseBody": {
        "description": "Data pertaining to the messages that clinicians send to the patients, and notes that are stored for internal use",
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/CareTeamResponse"
          }
        },
        "required": [
          "data"
        ]
      },
      "CareTeamResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "questionnaireResponseId": {
            "type": "string"
          },
          "isDraft": {
            "type": "boolean"
          },
          "responders": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Responder"
            }
          },
          "patientMessage": {
            "$ref": "#/components/schemas/PatientMessage"
          },
          "internalNote": {
            "type": "string",
            "description": "Optional note that the clinician can store for internal use",
            "nullable": true
          },
          "finalizedAt": {
            "type": "string",
            "format": "date-time",
            "description": "The date/time that the clinician finalized the documentation",
            "nullable": true
          },
          "submittedAt": {
            "type": "string",
            "format": "date-time",
            "description": "The date/time that the clinician sent the response to the patient",
            "nullable": true
          },
          "readAt": {
            "type": "string",
            "format": "date-time",
            "description": "The date/time that the patient read the response",
            "nullable": true
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "id",
          "questionnaireResponseId",
          "isDraft",
          "responders",
          "patientMessage",
          "createdAt",
          "updatedAt"
        ]
      },
      "Responder": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "providerId": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "action": {
            "$ref": "#/components/schemas/ResponderAction"
          }
        },
        "required": [
          "id",
          "action"
        ]
      },
      "PatientMessage": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "display": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          }
        },
        "required": [
          "code"
        ]
      },
      "FinalizeAction": {
        "description": "The action taken by the responder when they finalize a CareTeamResponse",
        "type": "string",
        "enum": [
          "SAVE",
          "SIGN"
        ]
      },
      "ResponderAction": {
        "type": "string",
        "enum": [
          "PATIENT_MESSAGE",
          "SAVE",
          "SIGN"
        ],
        "description": "Action taken by a responder on a CareTeamResponse"
      },
      "TenantConfiguration": {
        "type": "object",
        "properties": {
          "patientNotFoundCopy": {
            "type": "string",
            "description": "The copy to be rendered when the selected patient has not onboarded with Ronin"
          },
          "writeBackEnabled": {
            "type": "boolean",
            "description": "Whether a tenant is configured to allow for EHR write back."
          },
          "triageActions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TriageAction"
            }
          },
          "alertLevels": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AlertLevelConfiguration"
            }
          }
        },
        "required": [
          "writeBackEnabled",
          "triageActions",
          "alertLevels"
        ]
      },
      "TriageAction":{
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": "Computer-friendly representation of the triage action"
          },
          "display": {
            "type": "string",
            "description": "Human-friendly representation of the triage action"
          }
        },
        "required": [
          "code",
          "display"
        ]
      },
      "AlertLevelConfiguration": {
        "type": "object",
        "properties": {
          "level": {
            "type": "number"
          },
          "copy": {
            "type": "object",
            "properties": {
              "clinicianDashboard": {
                "type": "object",
                "properties": {
                  "additionalInfo": {
                    "type": "string"
                  }
                },
                "required": [
                  "additionalInfo"
                ]
              },
              "patientApp": {
                "type": "object",
                "properties": {
                  "header": {
                    "type": "object",
                    "properties": {
                      "icon":  {
                        "type": "string",
                        "description": "The red triangle with exclamation mark in the images above; this is a string used to identify the icon the client should use"
                      },
                      "backgroundColor": {
                        "type": "string",
                        "description": "The tan color behind the header icon and other surrounding text"
                      },
                      "text":  {
                        "type": "string",
                        "description": "The text to show in the header on successfully sending a message (Send to Care Team  in the first image)"
                      },
                      "color": {
                        "type": "string",
                        "description": "The color of the header title - Should be a hex string (e.g. #FFFFFF for white)"
                      },
                      "subtitle":  {
                        "type": "string",
                        "description": "The subtitle text that appears above the symptoms list (Your care team will be notified due to your respones for: in the first image)"
                      },
                      "subtitleColor": {
                        "type": "string",
                        "description": "The color of the symptoms subtitle"
                      }
                    },
                    "required": [
                      "icon",
                      "backgroundColor",
                      "text",
                      "color",
                      "subtitle",
                      "subtitleColor"
                    ]
                  },
                  "body": {
                    "type": "object",
                    "properties": {
                      "text": {
                        "type": "string",
                        "description": "The text to show in the body when message delivery is successful (You should expect a response within 24 hours, during clinic hours. in the second image)"
                      },
                      "color": {
                        "type":  "string",
                        "description": "The color of the text in the body title"
                      }
                    },
                    "required": [
                      "text",
                      "color"
                    ]
                  },
                  "footer": {
                    "type": "object",
                    "properties": {
                      "text": {
                        "type": "string",
                        "description": "The text to show in the footer at the bottom of each image"
                      }
                    },
                    "required": [
                      "text"
                    ]
                  }
                },
                "required": [
                  "header",
                  "body",
                  "footer"
                ]
              }
            },
            "required": [
              "clinicianDashboard",
              "patientApp"
            ]
          }
        },
        "required": [
          "level",
          "copy"
        ]
      },
      "TenantConfiguration_ResponseBody": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/TenantConfiguration"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Unique identifier for the error"
          },
          "title": {
            "type": "string",
            "description": "Human readable message the describes the type of failure"
          },
          "detailMessage": {
            "type": "string",
            "description": "Human readable message that describes the specific failure"
          },
          "detail": {
            "type": "object",
            "additionalProperties": true,
            "description": "An object that can convey structured information to the client. The schema of the object MUST be definable based on the code attribute",
            "nullable": true
          },
          "code": {
            "type": "string",
            "description": "An application specific error code string. This MAY be included if there is value providing an opaque error classification that can be used to lookup relevant documentation",
            "nullable": true
          },
          "status": {
            "type": "string",
            "description": "HTTP status of the response"
          }
        }
      }
    },
    "examples": {
      "QuestionnaireResponseEventResponseExample": {
        "summary": "Questionnaire Response Event Response Example",
        "value": {
          "patientId": "25e4822e-c289-11ed-afa1-0242ac120002",
          "tenantId": "5jzj62vp",
          "surveyResponseId": 19486,
          "symptoms": [
            "fatigue",
            "nausea"
          ],
          "writeIn": "blurry vision, sore throat",
          "alertState": "HIGH_ALERT",
          "qol": 50,
          "completedOn": "2022-09-13T12:14:15.000Z"
        }
      },
      "CreateCareTeamResponse_ResponseBody": {
        "summary": "Create Care Team Response Example",
        "value": {
          "data": {
            "id": "25e4822e-c289-11ed-afa1-0242ac120002",
            "questionnaireResponseId": "9970ca54-c289-11ed-afa1-0242ac120002",
            "isDraft": false,
            "responders": [
              {
                "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                "name": "Susan Smith",
                "action": "PATIENT_MESSAGE"
              }
            ],
            "patientId": "9d63650e-c289-11ed-afa1-0242ac120002",
            "patientMessage": {
              "code": "schedule_visit",
              "display": "Schedule Visit",
              "comment": "You should get in to see the doctor this week"
            },
            "internalNote": "Patient needs blood drawn",
            "readAt": null,
            "finalizedAt": null,
            "submittedAt": "2023-01-12T07:24:13.837Z",
            "createdAt": "2023-01-12T07:23:13.837Z",
            "updatedAt": "2023-01-12T07:24:13.837Z"
          }
        }
      },
      "MarkCareTeamResponsesAsRead_RequestBody": {
        "summary": "Mark Care Team Response as Read Request Body Example",
        "value": {
          "careTeamResponseIds": [
            "25e4822e-c289-11ed-afa1-0242ac120002"
          ]
        }
      },
      "FinalizeCareTeamResponse_RequestBody": {
        "summary": "Finalize Care Team Response Request Body Example",
        "value": {
          "internalNote": "Patient needs blood tests",
          "action": "SIGN",
          "ehrWriteBackMessage": "Diana Salazar reported symptoms through the Ronin Patient Symptom Monitoring App on 02/12/23 at 8:55pm PST\nSymptoms:\nDiarrhea: - Frequency: Most of the time - Episodes in last 24 hours: 4-6 - Blood in stool: No - Days present: 3 days - Taken Medication: Yes\nNausea: - Frequency: Most of the time - Severity: Severe - Interference with ADLs: Somewhat - Eating less: Yes - Taken Medication: No\nWrite-in: My diarrhea is continuing despite taking Imodium. I am not vomiting but I am so nauseated it hurts to move.\nI responded to the patient via the Ronin Symptom Monitoring App on 02/13/23 at 11:15am PST: We will call you to discuss in more detail within 24 hours. If the message was received outside of clinic hours, you may get a call the next day."
        }
      },
      "CareTeamRequestCutOver_RequestBody": {
        "summary": "An array of Care Team Responses",
        "value": {
          "questionnaireResponseId": "2138eef5-e29b-477c-a5b4-9a585b0a4382",
          "alertFeedbackId": "2138eef5-e29b-477c-a5b4-9a585b0a4382",
          "careTeamResponseId": "2138eef5-e29b-477c-a5b4-9a585b0a4382",
          "isDraft": false,
          "responder": {
            "id": "2cc29228-c281-11ed-afa1-0242ac120002",
            "name": "Susan Smith"
          },
          "patientMessage": {
            "code": "schedule_visit",
            "display": "Schedule Visit",
            "comment": "You should get in to see the doctor this week"
          },
          "readAt": null,
          "signedAt": null,
          "createdAt": "2023-01-12T07:23:13.837Z",
          "updatedAt": "2023-01-12T07:23:13.837Z"
        }
      },
      "DraftCareTeamResponse_ResponseBody": {
        "summary": "Draft Create Care Team Response Example",
        "value": {
          "data": {
            "id": "25e4822e-c289-11ed-afa1-0242ac120002",
            "questionnaireResponseId": "eef1b220-c754-11ed-afa1-0242ac120002",
            "isDraft": true,
            "responders": [
              {
                "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                "name": "Susan Smith",
                "action": "PATIENT_MESSAGE"
              }
            ],
            "patientId": "9d63650e-c289-11ed-afa1-0242ac120002",
            "patientMessage": {
              "code": "schedule_visit",
              "display": "Schedule Visit",
              "comment": "You should get in to see the doctor this week"
            },
            "internalNote": null,
            "readAt": null,
            "finalizedAt": null,
            "submittedAt": null,
            "createdAt": "2023-01-12T07:23:13.837Z",
            "updatedAt": "2023-01-12T07:23:13.837Z"
          }
        }
      },
      "FinalizeCareTeamResponse_ResponsBody": {
        "summary": "Finalize Care Team Response Example",
        "value": {
          "data": {
            "id": "25e4822e-c289-11ed-afa1-0242ac120002",
            "questionnaireResponseId": "9970ca54-c289-11ed-afa1-0242ac120002",
            "isDraft": false,
            "responders": [
              {
                "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                "name": "Susan Smith",
                "action": "PATIENT_MESSAGE"
              },
              {
                "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                "name": "Susan Smith",
                "action": "SIGN"
              }
            ],
            "patientId": "9d63650e-c289-11ed-afa1-0242ac120002",
            "patientMessage": {
              "code": "schedule_visit",
              "display": "Schedule Visit",
              "comment": "You should get in to see the doctor this week"
            },
            "internalNote": "Patient needs blood drawn",
            "readAt": null,
            "finalizedAt": "2023-01-12T07:23:13.837Z",
            "submittedAt": "2023-01-12T07:23:13.837Z",
            "createdAt": "2023-01-12T07:23:13.837Z",
            "updatedAt": "2023-01-12T07:23:13.837Z"
          }
        }
      },
      "UnreadCareTeamResponseCount_ResponseBody": {
        "summary": "Unread Care Team Response Count Example",
        "value": {
          "data": {
            "count": 1
          }
        }
      },
      "CareTeamResponse_RequestBody": {
        "description": "Create/update Care Team Request Body",
        "value": {
          "questionnaireResponseId": "fa3b78ce-c27b-11ed-afa1-0242ac120002",
          "patientMessage": {
            "code": "schedule_visit",
            "comment": "You should get in to see the doctor this week"
          }
        }
      },
      "FetchCareTeamResponses_ResponseBody": {
        "summary": "An array of Care Team Responses",
        "value": {
          "paging": {
            "page": 0,
            "limit": 20
          },
          "data": [
            {
              "id": "25e4822e-c289-11ed-afa1-0242ac120002",
              "questionnaireResponseId": "eef1b220-c754-11ed-afa1-0242ac120002",
              "isDraft": false,
              "responders": [
                {
                  "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                  "name": "Susan Smith",
                  "action": "PATIENT_MESSAGE"
                }
              ],
              "patientId": "9d63650e-c289-11ed-afa1-0242ac120002",
              "patientMessage": {
                "code": "schedule_visit",
                "display": "Schedule Visit",
                "comment": "You should get in to see the doctor this week"
              },
              "internalNote": "Patient needs blood drawn",
              "readAt": null,
              "finalizedAt": null,
              "submittedAt": null,
              "createdAt": "2023-01-12T07:23:13.837Z",
              "updatedAt": "2023-01-12T07:23:13.837Z"
            },
            {
              "id": "d3be912a-b694-4312-8451-e21b762cbac9",
              "questionnaireResponseId": "27ce169e-c280-11ed-afa1-0242ac120002",
              "isDraft": true,
              "responders": [
                {
                  "id": "2cc29228-c281-11ed-afa1-0242ac120002",
                  "name": "Susan Smith",
                  "action": "PATIENT_MESSAGE"
                },
                {
                  "id": "e1a4798f-a036-4e7b-ac80-fd8b959f57af",
                  "name": "Carson Johnson",
                  "action": "SIGN"
                }
              ],
              "patientId": "9d63650e-c289-11ed-afa1-0242ac120002",
              "patientMessage": {
                "code": "monitor_at_home",
                "display": "Monitor at Home"
              },
              "readAt": "2023-03-10T07:23:13.837Z",
              "finalizedAt": "2023-03-09T04:13:22.234Z",
              "submittedAt": "2023-03-09T04:13:22.234Z",
              "createdAt": "2023-02-15T07:23:13.837Z",
              "updatedAt": "2023-03-10T07:23:13.837Z"
            }
          ]
        }
      },
      "TenantConfiguration_ResponseBody": {
        "summary": "Tenant Configuration Response Body Example",
        "value": {
          "data": {
            "patientNotFoundCopy": "Send a MyChart message to this patient using the dot phrase .RONINONBOARDING to begin symptom monitoring at home.",
            "writeBackEnabled": true,
            "triageActions": [
              {
                "code": "monitor_at_home",
                "display": "Monitor at Home"
              },
              {
                "code": "schedule_visit",
                "display": "Schedule Visit"
              }
            ],
            "alertLevels": [
              {
                "level": 1,
                "copy": {
                  "clinicianDashboard": {
                    "additionalInfo": "Mild, Non-Alerted Symptom"
                  },
                  "patientApp": {
                    "header": {
                      "icon": "green-thumbs-up",
                      "backgroundColor": "#f4fff5",
                      "text": "Thank you! Reporting helps us monitor and manage your symptoms.",
                      "color": "#00830e",
                      "subtitle": "%{care_team_name} has your symptoms report in their records.",
                      "subtitleColor": "#000000"
                    },
                    "body": {
                      "text": "Continue to manage and monitor your symptoms at home.",
                      "color": "#116bff"
                    },
                    "footer": {
                      "text": "If you have new or worsening symptoms, or an emergency, please report them through this app, call your care team or 911."
                    }
                  }
                }
              }
            ]
          }
        }
      },
      "BadRequestError": {
        "summary": "Bad Request Error Example",
        "value": {
          "errors": [
            {
              "id": "179F5161-D264-422B-8E2E-72B721739922",
              "title": "Invalid Attribute",
              "detailMessage": "Attribute 'count' must be a positive value.",
              "code": "VALIDATE-25",
              "detail": {
                "field": "count",
                "value": "-1",
                "message": "Must be a positive value"
              },
              "status": "400"
            }
          ]
        }
      },
      "DuplicateResource": {
        "summary": "Bad Request - Duplicate Resource",
        "value": {
          "errors": [
            {
              "id": "179F5161-D264-422B-8E2E-72B721739922",
              "title": "Resource Already Exists",
              "detailMessage": "The care team response has already been stored and sent to the patient",
              "code": "DUPLICATE",
              "status": "400"
            }
          ]
        }
      },
      "DuplicateFinalization": {
        "value": {
          "errors": [
            {
              "id": "179F5161-D264-422B-8E2E-72B721739922",
              "title": "Response Already Finalized",
              "detailMessage": "The care team response has already been finalized by a provider",
              "code": "DUP_COMPLETION",
              "status": "409"
            }
          ]
        }
      },
      "NotFoundError": {
        "summary": "Resource Not Found Error Example",
        "value": {
          "errors": [
            {
              "id": "179F5161-D264-422B-8E2E-72B721739922",
              "title": "Resource Not Found",
              "detailMessage": "No questionnaire response with the ID \"10256\" found",
              "status": "404"
            }
          ]
        }
      },
      "InternalServerError": {
        "summary": "Internal Server Error",
        "value": {
          "errors": [
            {
              "id": "179F5161-D264-422B-8E2E-72B721739922",
              "title": "Internal Server Error",
              "detailMessage": "Lost connection with DB",
              "status": "500"
            }
          ]
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
